name: main
on: push
env:
  Python_version: '3.9.x'

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.Python_version }}
      - name: install boto3
        run: pip install boto3
      - name: install simplejson
        run: pip install simplejson
      - name: test getFunction
        run: cd resumesite/getFunction && python test.py -v ./ && cd ../../
      - name: test putFunction
        run: cd resumesite/putFunction && python test -v ./ && cd ../../

  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.Python_version }}
          check-latest: true
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - run: sam build
        working-directory: resumesite
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: resumesite

  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: www.thomasbaldock.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: resumesite/resumesitehtml