AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  resumesite
  Sample SAM Template for resumesite
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  MyWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: www.thomasbaldock.com

  MyWebsite2:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        RedirectAllRequestsTo: 
          HostName: www.thomasbaldock.com
          Protocol: https
      BucketName: thomasbaldock.com

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitors
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebsite
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::www.thomasbaldock.com/*'
            Condition:
              IpAddress:
                'aws:SourceIp':
                  - '2400:cb00::/32'
                  - '2405:8100::/32'
                  - '2405:b500::/32'
                  - '2606:4700::/32'
                  - '2803:f800::/32'
                  - '2a06:98c0::/29'
                  - '2c0f:f248::/32'
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 108.162.192.0/18
                  - 131.0.72.0/22
                  - 141.101.64.0/18
                  - 162.158.0.0/15
                  - 172.64.0.0/13
                  - 173.245.48.0/20
                  - 188.114.96.0/20
                  - 190.93.240.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17

#Create Get Lambda Function that pulls visitor count from my DynamoDB
  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: visitors
      CodeUri: getFunction/
      Handler: app.lambda_handler
      Runtime: python3.9.x
      Architectures:
        - x86_64
      Events:
        GetFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get
            Method: get

#Create Put Function that increases viewer count on refresh and stores new number in my DynamoDB Table
  PutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: visitors
      CodeUri: putFunction/
      Handler: app.lambda_handler
      Runtime: python3.9.x
      Architectures:
        - x86_64
      Events:
        PutFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /put
            Method: get
